spring:
  application:
    name: user
    
server:
  port: 8080
  
service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082,localhost:8083
    ServerListRefreshInterval: 15000
    